apiVersion: v1
kind: Service
metadata:
  name: haproxy-https-to-http
spec:
  type: NodePort
  selector:
    app: haproxy-https-to-http
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-https-to-http
data:
  haproxy.cfg: |
    global
        stats timeout 30s
        daemon

    defaults
        log     global
        mode    http
        timeout connect 5000
        timeout client  50000
        timeout server  50000

    frontend fe-http
        bind *:80
        mode http
        default_backend be-https

    backend be-https
      balance roundrobin
      server srv01 10.1.10.1:443 maxconn 100 check ssl verify none
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-https-to-http
spec:
  selector:
    matchLabels:
      app: haproxy-https-to-http
  replicas: 1
  template:
    metadata:
      name: haproxy-https-to-http
      labels:
        app: haproxy-https-to-http
    spec:
      containers:
        - name: haproxy-https-to-http
          image: haproxy
          ports:
            - containerPort: 80
          volumeMounts:
            - name: haproxy-https-to-http
              mountPath: /usr/local/etc/haproxy/haproxy.cfg
              subPath: haproxy.cfg
      volumes:
        - name: haproxy-https-to-http
          configMap:
           defaultMode: 0777
           name: haproxy-https-to-http
        - name: docker
          hostPath:
            path: /var/run/docker.sock